#import "../macros.typ" : *

In this chapter, we describe the low-level lexical structure of Haskell.
Most of the details may be skipped in a first reading of the report.

== Notational Conventions

These notational conventions are used for presenting syntax:

#let it(x) = text(style: "italic")[#x];

#table(
  columns: 2,
  align: (center,left),
  stroke: none,
  [\[#it("pattern")\]],[optional],
  [{#it("pattern")}],[zero or more repetitions],
  [(#it("pattern"))],[grouping],
  [#it("pat₁") | #it("pat₂")],[choice],
  [$italic("pat")_(chevron.l italic("pat'") chevron.r)$],[difference---elements generated by #it("pat") except those generated by #it("pat'")],
  [#terminal("fibonacci")],[terminal syntax in typewriter font],
)

Because the syntax in this section describes _lexical_ syntax, all
whitespace is expressed explicitly; there is no
implicit space between juxtaposed symbols.  BNF-like syntax is used
throughout, with productions having the form:

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  $italic("nonterm")$, $->$, $italic("alt₁") | italic("alt₂") | dots | italic("altₙ")$
)

Care must be taken in distinguishing metalogical syntax such as $|$
and $[dots]$ from concrete terminal syntax (given in typewriter font)
such as `|` and `[...]`, although usually the context makes the
distinction clear.

Haskell uses the Unicode @Unicode character set.
However, source  programs are currently biased toward the ASCII character set used in earlier versions of Haskell.

This syntax depends on properties of the Unicode characters as defined
by the Unicode consortium.
Haskell compilers are expected to make use of new versions of Unicode as they are made available.

== Lexical Program Structure

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // literal
  $italic("literal")$, $->$, $nonterminal("integer") | nonterminal("float") | nonterminal("char") | nonterminal("string")$,
  // special
  $italic("special")$, $->$, $terminal("(") | terminal(")") | terminal(",") | terminal(";") | terminal("[") | terminal("]") | terminal("`") | terminal("{") | terminal("}")$,
  // whitespace
  $italic("whitespace")$, $->$, $nonterminal("whitestuff") { nonterminal("whitestuff") }$,
  // whitestuff
  $italic("whitestuff")$, $->$, $nonterminal("whitechar") | nonterminal("comment") | nonterminal("ncomment")$,
  // whitechar
  $italic("whitechar")$, $->$, $nonterminal("newline") | nonterminal("vertab") | nonterminal("space") | nonterminal("tab") | nonterminal("uniWhite")$,
  // newline
  $italic("newline")$, $->$, $nonterminal("return") nonterminal("linefeed") | nonterminal("return") | nonterminal("linefeed") | nonterminal("formfeed")$,
  // return
  $italic("return")$, $->$, $text("a carriage return")$,
  // linefeed
  $italic("linefeed")$, $->$, $text("a line feed")$,
  // vertab
  $italic("vertab")$, $->$, $text("a vertical tab")$,
  // formfeed
  $italic("formfeed")$, $->$, $text("a form feed")$,
  // space
  $italic("space")$, $->$, $text("a space")$,
  // tab
  $italic("tab")$, $->$, $text("a horizontal tab")$,
  // uniWhite
  $italic("uniWhite")$, $->$, $text("any Unicode character defined as whitespace")$,
  // comment
  $italic("comment")$, $->$, $nonterminal("dashes") [nonterminal("any")_(chevron.l nonterminal("symbol") chevron.r) { nonterminal("any") }] nonterminal("newline")$,
  // dashes
  $italic("dashes")$, $->$, $terminal("--") { terminal("-") }$,
  // opencom
  $italic("opencom")$, $->$, $terminal("{-")$,
  // closecom
  $italic("closecom")$, $->$, $terminal("-}")$,
  // ncomment
  $italic("ncomment")$, $->$, $nonterminal("opencom") nonterminal("ANYseq") { nonterminal("ncomment") nonterminal("ANYseq") } nonterminal("closecom")$,
  // ANYseq
  $italic("ANYseq")$, $->$, ${ med nonterminal("ANY") med }_(chevron.l { med nonterminal("ANY") med } ( nonterminal("opencom") | nonterminal("closecom") ) { med nonterminal("ANY") med } chevron.r)$,
  // ANY
  $italic("ANY")$, $->$, $nonterminal("graphic") | nonterminal("whitechar")$,
  // any
  $italic("any")$, $->$, $nonterminal("graphic") | nonterminal("space") | nonterminal("tab")$,
  // graphic
  $italic("graphic")$, $->$, $nonterminal("small") | nonterminal("large") | nonterminal("symbol") | nonterminal("digit") | nonterminal("special") | terminal("\"") | terminal("'")$,
  // small
  $italic("small")$, $->$, $nonterminal("ascSmall") | nonterminal("uniSmall") | terminal("_")$,
  // ascSmall
  $italic("ascSmall")$, $->$, $terminal("a") | terminal("b") | dots | terminal("z")$,
  // uniSmall
  $italic("uniSmall")$, $->$, $text("any Unicode lowercase letter")$,
  // large
  $italic("large")$, $->$, $nonterminal("ascLarge") | nonterminal("uniLarge")$,
  // ascLarge
  $italic("ascLarge")$, $->$, $terminal("A") | terminal("B") | dots | terminal("Z")$,
  // uniLarge
  $italic("uniLarge")$, $->$, $text("any uppercase or titlecase Unicode letter")$,
  // symbol
  $italic("symbol")$, $->$, $nonterminal("ascSymbol") | nonterminal("uniSymbol")_(chevron.l nonterminal("special") | terminal("_") | terminal("\"") | terminal("'") chevron.r)$,
  // ascSymbol
  $italic("ascSymbol")$, $->$, $terminal("!") | terminal("#") | terminal("$") | terminal("%") | terminal("&") | terminal("*") | terminal("+") | terminal(".")  | terminal("/") | terminal("<") | terminal("=") | terminal(">") | terminal("?") | terminal("@")$,
  [], $|$, $terminal("\\") | terminal("^") | terminal("|") | terminal("-") | terminal("~") | terminal(":")$,
  // uniSymbol
  $italic("uniSymbol")$, $->$, $text("any Unicode symbol or punctuation")$,
  // digit
  $italic("digit")$, $->$, $nonterminal("ascDigit") | nonterminal("uniDigit")$,
  // ascDigit
  $italic("ascDigit")$, $->$, $terminal("0") | terminal("1") | dots | terminal("9")$,
  // uniDigit
  $italic("uniDigit")$, $->$, $text("any Unicode decimal digit")$,
  // octit
  $italic("octit")$, $->$, $terminal("0") | terminal("1") | dots | terminal("7")$,
  // hexit
  $italic("hexit")$, $->$, $nonterminal("digit") | terminal("A") | dots | terminal("F") | terminal("a") | dots | terminal("f")$,
)

Lexical analysis should use the ``maximal munch'' rule:
at each point, the longest possible lexeme
satisfying the $mono("lexeme")$ production is read.
So, although `case` is a reserved word, `cases` is not.
Similarly, although `=` is reserved, `==` and `~=` are not.

Any kind of $nonterminal("whitespace")$ is also a proper delimiter for lexemes.

Characters not in the category $nonterminal("ANY")$ are not valid
in Haskell programs and should result in a lexing error.

== Tokens <sec:tokens>

#table(
  columns: 4,
  stroke: none,
  align: (left, left, left, left),
  table.hline(),
  table.header([Token], [Category], [Definition],[Properties]),
  table.hline(),
  [#token("qvarid")],[Identifier],$nonterminal("qvarid")$,[Opening, Closing],
  [#token("qconid")],[Identifier],$nonterminal("qconid")$,[Opening, Closing],
  [#token("qvarsym")],[Identifier],$nonterminal("qvarsym")$,[Opening, Closing],
  [#token("qconsym")],[Identifier],$nonterminal("qconsym")$,[Opening, Closing],
  [#token("integer")],[Literal],$nonterminal("integer")$,[Opening, Closing],
  [#token("float")],[Literal],$nonterminal("float")$,[Opening, Closing],
  [#token("char")],[Literal],$nonterminal("char")$,[Opening, Closing],
  [#token("string")],[Literal],$nonterminal("string")$,[Opening, Closing],
  [#token("(")],[Special],$terminal("(")$,[Opening],
  [#token(")")],[Special],$terminal(")")$,[Closing],
  [#token(",")],[Special],$terminal(",")$,[],
  [#token(";")],[Special],$terminal(";")$,[],
  [#token("[")],[Special],$terminal("[")$,[Opening],
  [#token("]")],[Special],$terminal("]")$,[Closing],
  [#token("`")],[Special],$terminal("`")$,[],
  [#token("{")],[Special],$terminal("{")$,[Opening],
  [#token("}")],[Special],$terminal("}")$,[Closing],
  [#token("..")], [Reserved operator], $terminal("..")$,[],
  [#token(":")], [Reserved operator], $terminal(":")$,[],
  [#token("::")], [Reserved operator], $terminal("::")$,[],
  [#token("=")], [Reserved operator], $terminal("=")$,[],
  [#token("\\")], [Reserved operator], $terminal("\\")$,[],
  [#token("|")], [Reserved operator], $terminal("|")$,[],
  [#token("<-")], [Reserved operator], $terminal("<-")$,[],
  [#token("->")], [Reserved operator], $terminal("->")$,[],
  [#token("@")], [Reserved operator], $terminal("@")$,[],
  [#token("~")], [Reserved operator], $terminal("~")$,[],
  [#token("=>")], [Reserved operator], $terminal("=>")$,[],
  [#token("case")], [Reserved identifier], $terminal("case")$, [Opening, Closing],
  [#token("class")], [Reserved identifier], $terminal("class")$, [Opening, Closing],
  [#token("data")], [Reserved identifier], $terminal("data")$, [Opening, Closing],
  [#token("default")], [Reserved identifier], $terminal("default")$, [Opening, Closing],
  [#token("deriving")], [Reserved identifier], $terminal("deriving")$, [Opening, Closing],
  [#token("do")], [Reserved identifier], $terminal("do")$, [Opening, Closing],
  [#token("else")], [Reserved identifier], $terminal("else")$, [Opening, Closing],
  [#token("foreign")], [Reserved identifier], $terminal("foreign")$, [Opening, Closing],
  [#token("if")], [Reserved identifier], $terminal("if")$, [Opening, Closing],
  [#token("import")], [Reserved identifier], $terminal("import")$, [Opening, Closing],
  [#token("in")], [Reserved identifier], $terminal("in")$, [Opening, Closing],
  [#token("infix")], [Reserved identifier], $terminal("infix")$, [Opening, Closing],
  [#token("infixl")], [Reserved identifier], $terminal("infixl")$, [Opening, Closing],
  [#token("infixr")], [Reserved identifier], $terminal("infixr")$, [Opening, Closing],
  [#token("instance")], [Reserved identifier], $terminal("instance")$, [Opening, Closing],
  [#token("let")], [Reserved identifier], $terminal("let")$, [Opening, Closing],
  [#token("module")], [Reserved identifier], $terminal("module")$, [Opening, Closing],
  [#token("newtype")], [Reserved identifier], $terminal("newtype")$, [Opening, Closing],
  [#token("of")], [Reserved identifier], $terminal("of")$, [Opening, Closing],
  [#token("then")], [Reserved identifier], $terminal("then")$, [Opening, Closing],
  [#token("type")], [Reserved identifier], $terminal("type")$, [Opening, Closing],
  [#token("where")], [Reserved identifier], $terminal("where")$, [Opening, Closing],
  [#token("_")], [Reserved identifier], $terminal("_")$, [Opening, Closing],
  
)

== Comments

Comments are valid whitespace.

An ordinary comment begins with a sequence of
two or more consecutive dashes (e.g. `--`) and extends to the following newline.
_The sequence of dashes must not form part of a legal lexeme._
For example, "`-->`" or "`|--`" do _not_ begin
a comment, because both of these are legal lexemes; however "`--foo`" does start a comment.

A nested comment begins with "`{-`"
and ends with "`-}`".  No legal lexeme starts with "`{-`";
hence, for example, "`{---`" starts a nested comment despite the trailing dashes.

The comment itself is not lexically analysed.  Instead, the first
unmatched occurrence of the string "`-}`" terminates the nested comment.  Nested comments may be nested to any depth: any occurrence
of the string "`{-`" within the nested comment starts a new nested
comment, terminated by "`-}`".  Within a nested comment, each
"`{-`" is matched by a corresponding occurrence of "`-}`".

In an ordinary comment, the character
sequences "`{-`" and "`-}`" have no special significance, and, in a
nested comment, a sequence of dashes has no special significance.

Nested comments are also used for compiler pragmas, as explained in @chapter:compiler-pragmas.


If some code is commented out using a nested comment, then any
occurrence of `{-` or `-}` within a string or within an end-of-line
comment in that code will interfere with the nested comments.

== Identifiers and Operators <sec:ids>

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // varid
  $italic("varid")$, $->$, $(nonterminal("small") {nonterminal("small") | nonterminal("large") | nonterminal("digit") | terminal("'") med })_(chevron.l nonterminal("reservedid") chevron.r)$,
  // conid
  $italic("conid")$, $->$, $nonterminal("large") {nonterminal("small") | nonterminal("large") | nonterminal("digit") | terminal("'") med }$,
  // reservedid
  $italic("reservedid")$, $->$, $terminal("case") | terminal("class") | terminal("data") | terminal("default") | terminal("deriving") | terminal("do") | terminal("else")$,
  [], $|$, $terminal("foreign") | terminal("if") | terminal("import") | terminal("in") | terminal("infix") | terminal("infixl")$,
  [], $|$, $terminal("infixr") | terminal("instance") | terminal("let") | terminal("module") | terminal("newtype") | terminal("of")$,
  [], $|$, $terminal("then") | terminal("type") | terminal("where") | terminal("_")$,
)

An identifier consists of a letter followed by zero or more letters,
digits, underscores, and single quotes.  Identifiers are lexically
distinguished into two namespaces (@sec:namespaces): those that begin with a lowercase letter
(variable identifiers) and those that begin with an upper-case letter
(constructor identifiers).  Identifiers are case sensitive: `name`, `naMe`, and `Name` are three distinct identifiers (the first two are
variable identifiers, the last is a constructor identifier).

Underscore, "`_`", is treated as a lowercase letter, and can occur
wherever a lowercase letter can.  However, "`_`" all by itself is a
reserved identifier, used as wild card in patterns.  Compilers that offer
warnings for unused identifiers are encouraged to suppress such warnings for
identifiers beginning with underscore.  This allows programmers to use
"`_foo`" for a parameter that they expect to be unused.

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // varsym
  $italic("varsym")$, $->$, $( nonterminal("symbol")_(chevron.l terminal(":") chevron.r) { nonterminal("symbol")})_(chevron.l nonterminal("reservedop") | nonterminal("dashes") chevron.r)$,
  // consym
  $italic("consym")$, $->$, $(terminal(":") { nonterminal("symbol") })_(chevron.l nonterminal("reservedop") chevron.r)$,
  // reservedop
  $italic("reservedop")$, $->$, $terminal("..") | terminal(":") | terminal("::") | terminal("=") | terminal("\\") | terminal("|") | terminal("<-") | terminal("->") | terminal("@") | terminal("~") | terminal("=>")$,
)

_Operator symbols_
are formed from one or more symbol characters, as
defined above, and are lexically distinguished into two namespaces
(@sec:namespaces):

- An operator symbol starting with a colon is a constructor.
- An operator symbol starting with any other character is an ordinary identifier.

Notice that a colon by itself, "`:`", is reserved solely for use
as the Haskell list constructor; this makes its treatment uniform with
other parts of list syntax, such as "`[]`" and "`[a,b]`".

Other than the special syntax for prefix negation, all operators are
infix, although each infix operator can be used in a _section_ to yield partially applied operators (see @sec:sections).
All of the standard infix operators are just
predefined symbols and may be rebound.

In the remainder of the report six different kinds of
names will be used:

#table(
  columns: 4,
  align: (left, center, left, left),
  stroke: none,
  // varid
  $nonterminal("varid")$,[], [], [(variables)],
  // conid
  $nonterminal("conid")$,[],[],[(constructors)],
  // tyvar
  $italic("tyvar")$, $->$, $nonterminal("varid")$, [(type variables)],
  // tycon
  $italic("tycon")$, $->$, $nonterminal("conid")$, [(type constructors)],
  // tycls
  $italic("tycls")$, $->$, $nonterminal("conid")$, [(type classes)],
  // modid
  $italic("modid")$, $->$, ${ nonterminal("conid") terminal(".")} nonterminal("conid")$, [(modules)],
)

Variables and type variables are represented by identifiers beginning
with small letters, and the others by identifiers beginning with
capitals; also, variables and constructors have infix forms, the other
four do not.
Module names are a dot-separated sequence of $italic("conid")$s.
Namespaces are also discussed in @sec:namespaces.

A name may optionally be _qualified_ in certain
circumstances by prepending them with a module identifier.  This
applies to variable, constructor, type constructor and type class
names, but not type variables or module names.  Qualified
names are discussed in detail in @chapter:modules.

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // qvarid
  $italic("qvarid")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("varid")$,
  // qconid
  $italic("qconid")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("conid")$,
  // qtycon
  $italic("qtycon")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("tycon")$,
  // qtycls
  $italic("qtycls")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("tycls")$,
  // qvarysm
  $italic("qvarsym")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("varsym")$,
  // qconsym
  $italic("qconsym")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("consym")$,

)

Since a qualified name is a lexeme, no spaces are
allowed between the qualifier and the name.
Sample lexical analyses are shown below.

#table(
  columns: 2,
  align: (left, left),
  stroke: none,
  table.vline(x: 0),
  table.vline(x: 1),
  table.vline(x: 2),
  table.hline(),
  table.header([This], [Lexes as this]),
  table.hline(),
  [`f.g`],[`f . g` (three tokens)],
  [`F.g`],[`F.g` (qualified '`g`')],
  [`f..`],[`f ..` (two tokens)],
  [`F..`],[`F..` (qualified '`.`')],
  [`F.`],[`F .` (two tokens)],
  table.hline(),
)


The qualifier does not change the syntactic treatment of a name;
for example, `Prelude.+` is an infix operator with the same fixity as the
definition of `+` in the Prelude (@sec:fixity-declarations).


== Numeric Literals <sec:lexemes-numeric>

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // decimal
  $italic("decimal")$, $->$, $nonterminal("digit"){nonterminal("digit")}$,
  // octal
  $italic("octal")$, $->$, $nonterminal("octit"){nonterminal("octit")}$,
  // hexadecimal
  $italic("hexadecimal")$, $->$, $nonterminal("hexit"){nonterminal("hexit")}$,
  // integer
  $italic("integer")$, $->$, $nonterminal("decimal")$,
  [], $|$, $terminal("0o") nonterminal("octal") | terminal("0O") nonterminal("octal")$,
  [], $|$, $terminal("0x") nonterminal("hexadecimal") | terminal("0X") nonterminal("hexadecimal")$,
  // float
  $italic("float")$, $->$, $nonterminal("decimal") terminal(".") nonterminal("decimal") [ nonterminal("exponent")]$,
  [], $|$, $nonterminal("decimal") nonterminal("exponent")$,
  // exponent
  $italic("exponent")$, $->$, $(terminal("e") | terminal("E")) [terminal("+") | terminal("-")] nonterminal("decimal")$,
)

There are two distinct kinds of numeric literals: integer and
floating.  Integer literals may be given in decimal (the default),
octal (prefixed by `0o` or `0O`) or hexadecimal notation (prefixed by
`0x` or `0X`).
Floating literals are always decimal.
A floating literal must contain digits both before and after the
decimal point; this ensures that a decimal point cannot be mistaken
for another use of the dot character.  Negative numeric literals are
discussed in @sec:operator-applications.  The typing of numeric literals
is discussed in @sec:numeric-literals.

== Character and String Literals <sec:lexemes-char>

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // char
  $italic("char")$, $->$, $terminal("'") (nonterminal("graphic")_(chevron.l terminal("'") | terminal("\\") chevron.r) | nonterminal("space") | nonterminal("escape")_(chevron.l terminal("\&") chevron.r)) terminal("'")$,
  // string
  $italic("string")$, $->$, $terminal("\"") {nonterminal("graphic")_(chevron.l terminal("\"") | terminal("\\") chevron.r) | nonterminal("space") | nonterminal("escape") | nonterminal("gap") } terminal("\"")$,
  // escape
  $italic("escape")$, $->$, $terminal("\\") (nonterminal("charesc") | nonterminal("ascii") | nonterminal("decimal") | terminal("o") nonterminal("octal") | terminal("x") nonterminal("hexadecimal"))$,
  // charesc
  $italic("charesc")$, $->$, $terminal("a") | terminal("b") | terminal("f") | terminal("n") | terminal("r") | terminal("t") | terminal("v") | terminal("\\") | terminal("\"") | terminal("'") | terminal("&")$,
  // ascii
  $italic("ascii")$, $->$, $terminal("^") nonterminal("cntrl") | terminal("NUL") | terminal("SOH") | terminal("STX") | terminal("ETX") | terminal("EOT") | terminal("ENQ") | terminal("ACK")$,
  [], $|$, $terminal("BEL") | terminal("BS") | terminal("HT") | terminal("LF") | terminal("VT") | terminal("FF") | terminal("CR") | terminal("SO") | terminal("SI") | terminal("DLE")$,
  [], $|$, $terminal("DC1") | terminal("DC2") | terminal("DC3") | terminal("DC4") | terminal("NAK") | terminal("SYN") | terminal("ETB") | terminal("CAN")$,
  [], $|$, $terminal("EM") | terminal("SUB") | terminal("ESC") | terminal("FS") | terminal("GS") | terminal("RS") | terminal("US") | terminal("SP") | terminal("DEL")$,
  // cntrl
  $italic("cntrl")$, $->$, $nonterminal("ascLarge") | terminal("@") | terminal("[") | terminal("\\") | terminal("]") | terminal("^") | terminal("_")$,
  // gap
  $italic("gap")$, $->$, $terminal("\\") nonterminal("whitechar") { med nonterminal("whitechar") med } terminal("\\")$,
)

Character literals are written between single quotes, as in `'a'`, and strings between double quotes, as in `"Hello"`.

Escape codes may be used in characters and strings to represent
special characters.  Note that a single quote~`'` may be used in a string, but
must be escaped in a character; similarly, a double quote~`"` may be used in a
character, but must be escaped in a string. `\` must always be
escaped.  The category $italic("charesc")$ also includes portable
representations for the characters "alert" (`\a`), "backspace"
(`\b`), "form feed" (`\f`), "new line" (`\n`), "carriage return"
(`\r`), "horizontal tab" (`\t`), and "vertical tab" (`\v`).

Escape characters for the Unicode character
set, including
control characters such as `\^X`, are also provided.
Numeric escapes such as `\137` are used to designate the character
with decimal representation 137; octal
(e.g.~`\o137`) and hexadecimal (e.g.~`\x37`) representations are also allowed.

Consistent with the "maximal munch" rule,
numeric escape
characters in strings consist of all consecutive digits and may
be of arbitrary length.  Similarly, the one ambiguous ASCII escape
code, `"\SOH"`, is parsed as a string of length 1.  The escape
character `\&` is provided as a "null character" to allow strings
such as `"\137\&\9"` and `"\SO\&\H"` to be constructed (both of length two).  Thus `"\&"` is equivalent to `""` and the character `\&` is disallowed.  Further equivalences of characters are defined in @subsec:characters.

A string may include a "gap"---two backslants enclosing
white characters---which is ignored.
This allows one to write long strings on more than one line by writing
a backslant at the end of one line and at the start of the next.  For
example,
```
"Here is a backslant \\ as well as \137, \
    \a numeric escape character, and \^X, a control character."
```

String literals are actually abbreviations for lists of characters
(see @sec:lists).

== Layout <sec:lexemes-layout>

Haskell permits the omission of the braces and semicolons used in several
grammar productions, by
using _layout_ to convey the same information.  This allows both
layout-sensitive and layout-insensitive styles of coding, which
can be freely mixed within one program.  Because layout is
not required, Haskell programs can be straightforwardly
produced by other programs.

The effect of layout on the meaning of a Haskell program
can be completely specified by adding
braces and semicolons in places determined by the layout.  The meaning of
this augmented program is now layout insensitive.

Informally stated, the braces and semicolons are inserted as follows.
The layout (or "off-side") rule takes effect
whenever the open brace is omitted after the keyword `where`, `let`,
`do`, or
`of`.  When this happens, the indentation of the next lexeme (whether
or not on a new line) is remembered and the omitted open brace is
inserted (the whitespace preceding the lexeme may include comments).
For each subsequent line, if it contains only whitespace or is
indented more, then the previous item is continued (nothing is
inserted); if it is indented the same amount, then a new item begins
(a semicolon is inserted); and if it is indented less, then the
layout list ends (a close brace is inserted).  If the indentation of the
non-brace lexeme immediately following a `where`, `let`, `do` or `of` is less
than or equal to the current indentation level, then instead of starting
a layout, an empty list "`{}`" is inserted, and layout processing
occurs for the current level (i.e. insert a semicolon or close brace).
A close brace is
also inserted whenever the syntactic category containing the
layout list ends; that is, if an illegal lexeme is encountered at
a point where a close brace would be legal, a close brace is inserted.
The layout rule matches only those open braces that it has
inserted; an explicit open brace must be matched by
an explicit close brace.  Within these explicit open braces,
_no_ layout processing is performed for constructs outside the
braces, even if a line is
indented to the left of an earlier implicit open brace.

@sec:layout gives a more precise definition of the layout rules.

Given these rules, a single newline may actually terminate several
layout lists.  Also, these rules permit:
```haskell
f x = let a = 1; b = 2
          g y = exp2
       in exp1
```
making `a`, `b` and `g` all part of the same layout
list.

As an example, @fig:layout-before shows a (somewhat contrived)
module and @fig:layout-after shows the result of applying the
layout rule to it.  Note in particular: (a)~the line beginning `}};pop`,
where the termination of the previous line invokes three applications
of the layout rule, corresponding to the depth (3) of the nested
`where` clauses, (b)~the close braces in the `where` clause nested
within the tuple and `case` expression, inserted because the end of the
tuple was detected, and (c)~the close brace at the very end, inserted
because of the column 0 indentation of the end-of-file token.

#figure(
  caption: "A sample program",
  supplement: "Figure"
)[
```haskell
module AStack( Stack, push, pop, top, size ) where
data Stack a = Empty
             | MkStack a (Stack a)

push :: a -> Stack a -> Stack a
push x s = MkStack x s

size :: Stack a -> Int
size s = length (stkToLst s)  where
           stkToLst  Empty         = []
           stkToLst (MkStack x s)  = x:xs where xs = stkToLst s

pop :: Stack a -> (a, Stack a)
pop (MkStack x s)
  = (x, case s of r -> i r where i x = x) -- (pop Empty) is an error

top :: Stack a -> a
top (MkStack x s) = x                     -- (top Empty) is an error
```
]<fig:layout-before>

#figure(
  caption: "Sample program with layout expanded",
  supplement: "Figure"
)[
```haskell
module AStack( Stack, push, pop, top, size ) where
{data Stack a = Empty
             | MkStack a (Stack a)

;push :: a -> Stack a -> Stack a
;push x s = MkStack x s

;size :: Stack a -> Int
;size s = length (stkToLst s)  where
           {stkToLst  Empty         = []
           ;stkToLst (MkStack x s)  = x:xs where {xs = stkToLst s

}};pop :: Stack a -> (a, Stack a)
;pop (MkStack x s)
  = (x, case s of {r -> i r where {i x = x}}) -- (pop Empty) is an error

;top :: Stack a -> a
;top (MkStack x s) = x                        -- (top Empty) is an error
}
```
]<fig:layout-after>