#import "../macros.typ" : *

== Notational Conventions

These notational conventions are used for presenting syntax:

#let it(x) = text(style: "italic")[#x];

#table(
  columns: 2,
  align: (center,left),
  stroke: none,
  [\[#it("pattern")\]],[optional],
  [{#it("pattern")}],[zero or more repetitions],
  [(#it("pattern"))],[grouping],
  [#it("pat₁") | #it("pat₂")],[choice],
  [$italic("pat")_(chevron.l italic("pat'") chevron.r)$],[difference---elements generated by #it("pat") except those generated by #it("pat'")],
  [#terminal("fibonacci")],[terminal syntax in typewriter font],
)

BNF-like syntax is used throughout, with productions having the form:

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  $italic("nonterm")$, $->$, $italic("alt₁") | italic("alt₂") | dots | italic("altₙ")$
)

In both the lexical and the context-free syntax, there are some
ambiguities that are to be resolved by making grammatical phrases as
long as possible, proceeding from left to right (in shift-reduce
parsing, resolving shift/reduce conflicts by shifting).  In the lexical
syntax, this is the "maximal munch" rule.  In the
context-free syntax, this means that conditionals, let-expressions, and
lambda abstractions extend to the right as far as possible.

== Lexical Syntax

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // program
  $nonterminaldef("program")$, $->$, ${ med nonterminal("lexeme") | nonterminal("whitespace") med }$,
  // lexeme
  $nonterminaldef("lexeme")$, $->$, $nonterminal("qvarid") | nonterminal("qconid") | nonterminal("qvarsym") | nonterminal("qconsym")$,
  [], $|$, $nonterminal("literal") | nonterminal("special") | nonterminal("reservedop") | nonterminal("reservedid")$,
  // literal
  $nonterminaldef("literal")$, $->$, $nonterminal("integer") | nonterminal("float") | nonterminal("char") | nonterminal("string")$,
  // special
  $nonterminaldef("special")$, $->$, $terminal("(") | terminal(")") | terminal(",") | terminal(";") | terminal("[") | terminal("]") | terminal("`") | terminal("{") | terminal("}")$,
  // whitespace
  $nonterminaldef("whitespace")$, $->$, $nonterminal("whitestuff") { nonterminal("whitestuff") }$,
  // whitestuff
  $nonterminaldef("whitestuff")$, $->$, $nonterminal("whitechar") | nonterminal("comment") | nonterminal("ncomment")$,
  // whitechar
  $nonterminaldef("whitechar")$, $->$, $nonterminal("newline") | nonterminal("vertab") | nonterminal("space") | nonterminal("tab") | nonterminal("uniWhite")$,
  // newline
  $nonterminaldef("newline")$, $->$, $nonterminal("return") nonterminal("linefeed") | nonterminal("return") | nonterminal("linefeed") | nonterminal("formfeed")$,
  // return
  $nonterminaldef("return")$, $->$, $text("a carriage return")$,
  // linefeed
  $nonterminaldef("linefeed")$, $->$, $text("a line feed")$,
  // vertab
  $nonterminaldef("vertab")$, $->$, $text("a vertical tab")$,
  // formfeed
  $nonterminaldef("formfeed")$, $->$, $text("a form feed")$,
  // space
  $nonterminaldef("space")$, $->$, $text("a space")$,
  // tab
  $nonterminaldef("tab")$, $->$, $text("a horizontal tab")$,
  // uniWhite
  $nonterminaldef("uniWhite")$, $->$, $text("any Unicode character defined as whitespace")$,
  // comment
  $nonterminaldef("comment")$, $->$, $nonterminal("dashes") [nonterminal("any")_(chevron.l nonterminal("symbol") chevron.r) { nonterminal("any") }] nonterminal("newline")$,
  // dashes
  $nonterminaldef("dashes")$, $->$, $terminal("--") { terminal("-") }$,
  // opencom
  $nonterminaldef("opencom")$, $->$, $terminal("{-")$,
  // closecom
  $nonterminaldef("closecom")$, $->$, $terminal("-}")$,
  // ncomment
  $nonterminaldef("ncomment")$, $->$, $nonterminal("opencom") nonterminal("ANYseq") { nonterminal("ncomment") nonterminal("ANYseq") } nonterminal("closecom")$,
  // ANYseq
  $nonterminaldef("ANYseq")$, $->$, ${ med nonterminal("ANY") med }_(chevron.l { med nonterminal("ANY") med } ( nonterminal("opencom") | nonterminal("closecom") ) { med nonterminal("ANY") med } chevron.r)$,
  // ANY
  $nonterminaldef("ANY")$, $->$, $nonterminal("graphic") | nonterminal("whitechar")$,
  // any
  $nonterminaldef("any")$, $->$, $nonterminal("graphic") | nonterminal("space") | nonterminal("tab")$,
  // graphic
  $nonterminaldef("graphic")$, $->$, $nonterminal("small") | nonterminal("large") | nonterminal("symbol") | nonterminal("digit") | nonterminal("special") | terminal("\"") | terminal("'")$,
  // small
  $nonterminaldef("small")$, $->$, $nonterminal("ascSmall") | nonterminal("uniSmall") | terminal("_")$,
  // ascSmall
  $nonterminaldef("ascSmall")$, $->$, $terminal("a") | terminal("b") | dots | terminal("z")$,
  // uniSmall
  $nonterminaldef("uniSmall")$, $->$, $text("any Unicode lowercase letter")$,
  // large
  $nonterminaldef("large")$, $->$, $nonterminal("ascLarge") | nonterminal("uniLarge")$,
  // ascLarge
  $nonterminaldef("ascLarge")$, $->$, $terminal("A") | terminal("B") | dots | terminal("Z")$,
  // uniLarge
  $nonterminaldef("uniLarge")$, $->$, $text("any uppercase or titlecase Unicode letter")$,
  // symbol
  $nonterminaldef("symbol")$, $->$, $nonterminal("ascSymbol") | nonterminal("uniSymbol")_(chevron.l nonterminal("special") | terminal("_") | terminal("\"") | terminal("'") chevron.r)$,
  // ascSymbol
  $nonterminaldef("ascSymbol")$, $->$, $terminal("!") | terminal("#") | terminal("$") | terminal("%") | terminal("&") | terminal("*") | terminal("+") | terminal(".")  | terminal("/") | terminal("<") | terminal("=") | terminal(">") | terminal("?") | terminal("@")$,
  [], $|$, $terminal("\\") | terminal("^") | terminal("|") | terminal("-") | terminal("~") | terminal(":")$,
  // uniSymbol
  $nonterminaldef("uniSymbol")$, $->$, $text("any Unicode symbol or punctuation")$,
  // digit
  $nonterminaldef("digit")$, $->$, $nonterminal("ascDigit") | nonterminal("uniDigit")$,
  // ascDigit
  $nonterminaldef("ascDigit")$, $->$, $terminal("0") | terminal("1") | dots | terminal("9")$,
  // uniDigit
  $nonterminaldef("uniDigit")$, $->$, $text("any Unicode decimal digit")$,
  // octit
  $nonterminaldef("octit")$, $->$, $terminal("0") | terminal("1") | dots | terminal("7")$,
  // hexit
  $nonterminaldef("hexit")$, $->$, $nonterminal("digit") | terminal("A") | dots | terminal("F") | terminal("a") | dots | terminal("f")$,
)

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // varid
  $nonterminaldef("varid")$, $->$, $(nonterminal("small") {nonterminal("small") | nonterminal("large") | nonterminal("digit") | terminal("'") med })_(chevron.l nonterminal("reservedid") chevron.r)$,
  // conid
  $nonterminaldef("conid")$, $->$, $nonterminal("large") {nonterminal("small") | nonterminal("large") | nonterminal("digit") | terminal("'") med }$,
  // reservedid
  $nonterminaldef("reservedid")$, $->$, $terminal("case") | terminal("class") | terminal("data") | terminal("default") | terminal("deriving") | terminal("do") | terminal("else")$,
  [], $|$, $terminal("forall") | terminal("foreign") | terminal("if") | terminal("import") | terminal("in") | terminal("infix") | terminal("infixl")$,
  [], $|$, $terminal("infixr") | terminal("instance") | terminal("let") | terminal("module") | terminal("newtype") | terminal("of")$,
  [], $|$, $terminal("then") | terminal("type") | terminal("where") | terminal("_")$,
)

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // varsym
  $nonterminaldef("varsym")$, $->$, $( nonterminal("symbol")_(chevron.l terminal(":") chevron.r) { nonterminal("symbol")})_(chevron.l nonterminal("reservedop") | nonterminal("dashes") chevron.r)$,
  // consym
  $nonterminaldef("consym")$, $->$, $(terminal(":") { nonterminal("symbol") })_(chevron.l nonterminal("reservedop") chevron.r)$,
  // reservedop
  $nonterminaldef("reservedop")$, $->$, $terminal("..") | terminal(":") | terminal("::") | terminal("=") | terminal("\\") | terminal("|") | terminal("<-") | terminal("->") | terminal("@") | terminal("~") | terminal("=>")$,
)

#table(
  columns: 4,
  align: (left, center, left, left),
  stroke: none,
  // varid
  $nonterminal("varid")$,[], [], [(variables)],
  // conid
  $nonterminal("conid")$,[],[],[(constructors)],
  // tyvar
  $nonterminaldef("tyvar")$, $->$, $nonterminal("varid")$, [(type variables)],
  // tycon
  $nonterminaldef("tycon")$, $->$, $nonterminal("conid")$, [(type constructors)],
  // tycls
  $nonterminaldef("tycls")$, $->$, $nonterminal("conid")$, [(type classes)],
  // modid
  $nonterminaldef("modid")$, $->$, ${ nonterminal("conid") terminal(".")} nonterminal("conid")$, [(modules)],
)

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // qvarid
  $nonterminaldef("qvarid")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("varid")$,
  // qconid
  $nonterminaldef("qconid")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("conid")$,
  // qtycon
  $nonterminaldef("qtycon")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("tycon")$,
  // qtycls
  $nonterminaldef("qtycls")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("tycls")$,
  // qvarysm
  $nonterminaldef("qvarsym")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("varsym")$,
  // qconsym
  $nonterminaldef("qconsym")$, $->$, $[nonterminal("modid") terminal(".")] nonterminal("consym")$,

)

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // decimal
  $nonterminaldef("decimal")$, $->$, $nonterminal("digit"){nonterminal("digit")}$,
  // octal
  $nonterminaldef("octal")$, $->$, $nonterminal("octit"){nonterminal("octit")}$,
  // hexadecimal
  $nonterminaldef("hexadecimal")$, $->$, $nonterminal("hexit"){nonterminal("hexit")}$,
  // integer
  $nonterminaldef("integer")$, $->$, $nonterminal("decimal")$,
  [], $|$, $terminal("0o") nonterminal("octal") | terminal("0O") nonterminal("octal")$,
  [], $|$, $terminal("0x") nonterminal("hexadecimal") | terminal("0X") nonterminal("hexadecimal")$,
  // float
  $nonterminaldef("float")$, $->$, $nonterminal("decimal") terminal(".") nonterminal("decimal") [ nonterminal("exponent")]$,
  [], $|$, $nonterminal("decimal") nonterminal("exponent")$,
  // exponent
  $nonterminaldef("exponent")$, $->$, $(terminal("e") | terminal("E")) [terminal("+") | terminal("-")] nonterminal("decimal")$,
)

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  // char
  $nonterminaldef("char")$, $->$, $terminal("'") (nonterminal("graphic")_(chevron.l terminal("'") | terminal("\\") chevron.r) | nonterminal("space") | nonterminal("escape")_(chevron.l terminal("\&") chevron.r)) terminal("'")$,
  // string
  $nonterminaldef("string")$, $->$, $terminal("\"") {nonterminal("graphic")_(chevron.l terminal("\"") | terminal("\\") chevron.r) | nonterminal("space") | nonterminal("escape") | nonterminal("gap") } terminal("\"")$,
  // escape
  $nonterminaldef("escape")$, $->$, $terminal("\\") (nonterminal("charesc") | nonterminal("ascii") | nonterminal("decimal") | terminal("o") nonterminal("octal") | terminal("x") nonterminal("hexadecimal"))$,
  // charesc
  $nonterminaldef("charesc")$, $->$, $terminal("a") | terminal("b") | terminal("f") | terminal("n") | terminal("r") | terminal("t") | terminal("v") | terminal("\\") | terminal("\"") | terminal("'") | terminal("&")$,
  // ascii
  $nonterminaldef("ascii")$, $->$, $terminal("^") nonterminal("cntrl") | terminal("NUL") | terminal("SOH") | terminal("STX") | terminal("ETX") | terminal("EOT") | terminal("ENQ") | terminal("ACK")$,
  [], $|$, $terminal("BEL") | terminal("BS") | terminal("HT") | terminal("LF") | terminal("VT") | terminal("FF") | terminal("CR") | terminal("SO") | terminal("SI") | terminal("DLE")$,
  [], $|$, $terminal("DC1") | terminal("DC2") | terminal("DC3") | terminal("DC4") | terminal("NAK") | terminal("SYN") | terminal("ETB") | terminal("CAN")$,
  [], $|$, $terminal("EM") | terminal("SUB") | terminal("ESC") | terminal("FS") | terminal("GS") | terminal("RS") | terminal("US") | terminal("SP") | terminal("DEL")$,
  // cntrl
  $nonterminaldef("cntrl")$, $->$, $nonterminal("ascLarge") | terminal("@") | terminal("[") | terminal("\\") | terminal("]") | terminal("^") | terminal("_")$,
  // gap
  $nonterminaldef("gap")$, $->$, $terminal("\\") nonterminal("whitechar") { med nonterminal("whitechar") med } terminal("\\")$,
)

== Layout <sec:layout>

@sec:lexemes-layout gives an informal discussion of the layout
rule. This section defines it more precisely.

The meaning of a Haskell program may depend on its _layout_.
The effect of layout on its meaning can be completely described by adding
braces and semicolons in places determined by the layout.
The meaning of this augmented program is now layout insensitive.

The effect of layout is specified in this section by describing
how to add braces and semicolons to a laid-out program.  The specification
takes the form of a function $L$ that performs the translation.
The input to $L$ is:
- A stream of lexemes as specified by the lexical syntax in the Haskell report, with the following additional tokens: 
  - If a `let`, `where`, `do`, or `of` keyword is not followed by the lexeme `{`, 
    the token `{n}` is inserted after the keyword, where $n$ is the indentation of the 
    next lexeme if there is one, or $0$ if the end of file has been reached.
  - If the first lexeme of a module is not `{` or `module`, 
    then it is preceded by `{n}` where $n$ is the indentation of the lexeme. 
  - Where the start of a lexeme is preceded only by white space on the
    same line, this lexeme is preceded by $italic("<n>")$ where $n$
    is the indentation of the lexeme, provided that it is not,
    as a consequence of the first two rules, preceded by `{n}`.
    (NB: a string literal may span multiple lines -- @sec:lexemes-char.  So in the fragment
    ```
    f = ("Hello \
          \Bill", "Jake")
    ```
    There is no $italic("<n>")$ inserted before the `\Bill`, because it is not the beginning of
    a complete lexeme; nor before the `,`, because it is not preceded only by white space.)
- A stack of "layout contexts", in which each element is either:
  - Zero, indicating that the enclosing context is explicit (i.e. the programmer 
    supplied the opening brace). 
    If the innermost context is 0, then no layout tokens will be inserted 
    until either the enclosing context ends or a new context is pushed. 
  - A positive integer, which is the indentation column of the enclosing layout context. 

The "indentation" of a lexeme is the column number
of the first character of that lexeme; the indentation of a line is the
indentation of its leftmost lexeme.  To determine the column number,
assume a fixed-width font with the following conventions:

- The characters $italic("newline")$, $italic("return")$, $italic("linefeed")$, and $italic("formfeed")$, all start a new line.
- The first column is designated column 1, not 0.
- Tab stops are 8 characters apart.
- A tab character causes the insertion of
  enough spaces to align the current position with the next tab stop.

For the purposes of the layout rule, Unicode characters in a source program
are considered to be of the same, fixed, width as an ASCII character.
However, to avoid visual confusion, programmers should avoid writing programs in which 
the meaning of implicit layout depends on the width of non-space characters.

The application
```
L tokens []
```
delivers a layout-insensitive translation of $italic("tokens")$, where $italic("tokens")$
is the result of lexically analysing a module and adding column-number
indicators to it as described above.
The definition of $L$ is as follows, where we use "`:`" as a stream
construction operator, and "`[]`" for the empty stream.

#table(
  columns: 4,
  align: (left, center, left, left),
  stroke: none,
  [`L(<n>:ts)(m:ms)`],[`=`],[`; : (L ts (m : ms))`],[if $m = n$],
  [], [`=`], [`} : (L(<n>:ts) ms)`], [if $n < m$],
  [`L(<n>:ts) ms`],[`=`],[`L ts ms`],[],
  [`L({n} : ts)(m:ms)`],[`=`],[`{ : (L ts (n : m : ms)`], [if $n > m$ (Note 1)],
  [`L({n} : ts)[]`], [`=`],[`{ : (L ts [n])`], [if $n > 0$ (Note 1)],
  [`L({n} : ts) ms`], [`=`],[`{ : } : (L (<n> : ts) ms)`], [(Note 2)],
  [`L(} : ts)(0:ms)`], [`=`],[`} : (L ts ms)`],[(Note 3)],
  [`L(} : ts) ms`], [`=`], [parse-error], [(Note 3)],
  [`L({ : ts) ms`], [`=`], [`{ : (L ts (0 : ms))`],[(Note 4)],
  [`L(t : ts)(m:ms)`], [`=`], [`} : (L (t:ts) ms)`],[if `m /= 0` and parse-error($t$) (Note 5)],
  [`L(t : ts) ms`], [`=`], [`t : (L ts ms)`], [],
  [`L [] []`], [`=`], [`[]`],[],
  [`L [] (m : ms)`],[`=`],[`} : (L [] ms)`],[if $m != 0$ (Note 6)]
)

/ Note 1.: A nested context must be further indented 
  than the enclosing context ($n>m$). If not, $L$ fails, and the compiler should indicate a
  layout error.  An example is:
  ```haskell
  f x = let
           h y = let
    p z = z
                 in p
        in h
  ```
  Here, the definition of `p` is indented less than the indentation of
  the enclosing context, which is set in this case by the definition of `h`.

/ Note 2.: If the first token after a `where` (say) is not indented more
  than the enclosing layout context, then the block must be empty, so empty
  braces are inserted.  The $\{n\}$ token is replaced by $<n>$, to mimic the
  situation if the empty braces had been explicit.

/ Note 3.: By matching against 0 for the current layout context, 
  we ensure that an explicit close brace can only match an explicit open brace. 
  A parse error results if an explicit close brace matches an implicit open brace.

/ Note 4.: This clause means that all brace pairs are treated as explicit layout 
  contexts, including labelled construction and update (@sec:field-ops). 
  This is a difference between this formulation and Haskell 1.4.

/ Note 5.: The side condition $italic("parse-error") (t)$ is to be interpreted as follows: 
  if the tokens generated so far by $L$ together with the next token $t$ 
  represent an invalid prefix of the Haskell grammar, and the 
  tokens generated so far by $L$ followed by the token "`}`" represent a valid prefix of the Haskell grammar, then $italic("parse-error")(t)$ is true. 

  The test `m /= 0` checks that an implicitly-added closing brace would match
  an implicit open brace.
/ Note 6.: At the end of the input, any pending close-braces are inserted. 
  It is an error at this point to be within a non-layout context (i.e. $m = 0$). 


If none of the rules given above matches, then the algorithm fails. It
can fail for instance when the end of the input is reached, and a
non-layout context is active, since the close brace is missing. Some
error conditions are not detected by the algorithm, although they
could be: for example `let }`.

Note 1 implements the feature that layout processing can be stopped
prematurely by a parse error.  For example
```haskell
let x = e; y = x in e'
```
is valid, because it translates to 
```haskell
let { x = e; y = x } in e'
```
The close brace is inserted due to the parse error rule above.

== Literate comments

The "literate comment"
convention, first developed by Richard Bird and Philip Wadler for
Orwell, and inspired in turn by Donald Knuth's "literate
programming", is an alternative style for encoding Haskell source code. 
The literate style encourages comments by making them the default.  A
line in which "`>`" is the first character is treated as part of the
program; all other lines are comments.

The program text is recovered
by taking only those lines beginning with "`>`", 
and replacing the leading "`>`" with a space.
Layout and comments apply exactly as described in @chapter:syntax-reference in the resulting text.

To capture some cases where one omits an "`>`" by mistake, it is an
error for a program line to appear adjacent to a non-blank comment line,
where a line is taken as blank if it consists only of whitespace.

By convention, the style of comment is indicated by the file
extension, with "`.hs`" indicating a usual Haskell file and "`.lhs`" indicating a literate Haskell file.  Using this style, a
simple factorial program would be:
```
   This literate program prompts the user for a number
   and prints the factorial of that number:

> main :: IO ()

> main = do putStr "Enter a number: "
>           l <- readLine
>           putStr "n!= "
>           print (fact (read l))
          
  This is the factorial function.

> fact :: Integer -> Integer
> fact 0 = 1
> fact n = n * fact (n-1)
```


An alternative style of literate programming is particularly
suitable for use with the LaTeX text processing system.
In this convention, only those parts of the literate program that are
entirely enclosed between `\begin{code}...\end{code}` delimiters are treated as program text; all other lines are comments.  More precisely:

- Program code begins on the first line following a line that begins `\begin{code}`.
- Program code ends just before a subsequent line that begins `\end{code}` (ignoring
  string literals, of course).

It is not necessary to insert additional blank lines before or after these delimiters, though it may be stylistically desirable.
For example,

```latex
\documentstyle{article}

\begin{document}

\chapter{Introduction}

This is a trivial program that prints the first 20 factorials.

\begin{code}
main :: IO ()
main =  print [ (n, product [1..n]) | n <- [1..20]]
\end{code}

\end{document}
```

This style uses the same file extension.  It is not advisable to mix
these two styles in the same file.

== Context-Free Syntax

#table(
  columns: 4,
  align: (left, center, left, left),
  stroke: none,
  // module
  $nonterminaldef("module")$, $->$, $terminal("module") nonterminal("modid") [ nonterminal("exports")] terminal("where") nonterminal("body")$,$$,
  $$, $|$, $nonterminal("body")$, $$,
  // body
  $nonterminaldef("body")$, $->$, $terminal("{") nonterminal("impdecls") terminal(";") nonterminal("topdecls") terminal("}")$, $$,
  $$, $|$, $terminal("{") nonterminal("impdecls") terminal("}")$, $$,
  $$, $|$, $terminal("{") nonterminal("topdecls") terminal("}")$, $$,
  // impdecls
  $nonterminaldef("impdecls")$, $->$, $nonterminal("impdecl")_1 terminal(";") dots terminal(";") nonterminal("impdecl")_n$, $(n >= 1)$,
  // exports
  $nonterminaldef("exports")$, $->$, $terminal("(") nonterminal("export")_1 terminal(",") dots terminal(",") nonterminal("export")_n [terminal(",")]terminal(")")$, $(n >= 0)$,
  // export
  $nonterminaldef("export")$, $->$, $nonterminal("qvar")$, $$,
  $$, $|$, $nonterminal("qtycon") [ terminal("(..)") | terminal("(") nonterminal("cname")_1 terminal(",") dots terminal(",") nonterminal("cname")_n terminal(")")]$, $(n >= 0)$,
  $$, $|$, $nonterminal("qtycls") [ terminal("(..)") | terminal("(") nonterminal("var")_1 terminal(",") dots terminal(",") nonterminal("var")_n terminal(")")]$, $(n >= 0)$,
  $$, $|$, $terminal("module") nonterminal("modid")$, $$,
  // impdecl
  $nonterminaldef("impdecl")$, $->$, $terminal("import") [terminal("qualified")] nonterminal("modid") [terminal("as") nonterminal("modid")] [nonterminal("impspec")]$, $$,
  $$, $|$, $$, [(empty declaration)],
  // impspec
  $nonterminaldef("impspec")$, $->$, $terminal("(") nonterminal("import")_1 terminal(",") dots terminal(",") nonterminal("import")_n [terminal(",")] terminal(")")$, $(n >= 0)$,
  $$, $|$, $terminal("hiding") terminal("(") nonterminal("import")_1 terminal(",") dots terminal(",") nonterminal("import")_n [terminal(",")] terminal(")")$, $(n >= 0)$,
  // import
  $nonterminaldef("import")$, $->$, $nonterminal("var")$, $$,
  $$, $|$, $nonterminal("tycon") [ terminal("(..)") | terminal("(") nonterminal("cname")_1 terminal(",") dots terminal(",") nonterminal("cname")_n terminal(")")]$, $(n >= 0)$,
  $$, $|$, $nonterminal("tycls") [ terminal("(..)") | terminal("(") nonterminal("var")_1 terminal(",") dots terminal(",") nonterminal("var")_n terminal(")")]$, $(n >= 0)$,
  // cname
  $nonterminaldef("cname")$, $->$, $ nonterminal("var") | nonterminal("con")$, $$,
  // topdecls
  $nonterminaldef("topdecls")$, $->$, $nonterminal("topdecl")_1 terminal(";") dots terminal(";") nonterminal("topdecl")_n$, $(n >= 1)$,
  // topdecl
  $nonterminaldef("topdecl")$, $->$, $terminal("type") nonterminal("simpletype") terminal("=") nonterminal("type")$, $$,
  $$, $|$, $terminal("data") [nonterminal("context") terminal("=>")] nonterminal("simpletype") [terminal("=") nonterminal("constrs")] [nonterminal("deriving")]$, $$,
  $$, $|$, $terminal("newtype") [nonterminal("context") terminal("=>")] nonterminal("simpletype") terminal("=") nonterminal("newconstr") [nonterminal("deriving")]$, $$,
  $$, $|$, $terminal("class") [nonterminal("scontext") terminal("=>")] nonterminal("tycls") nonterminal("tyvar") [terminal("where") nonterminal("cdecls")]$, $$,
  $$, $|$, $terminal("instance") [nonterminal("scontext") terminal("=>")] nonterminal("qtycls") nonterminal("inst") [terminal("where") nonterminal("idecls")]$, $$,
  $$, $|$, $terminal("default") terminal("(") nonterminal("type")_1 terminal(",") dots terminal(",") nonterminal("type")_n terminal(")")$, $(n >= 0)$,
  $$, $|$, $terminal("foreign") nonterminal("fdecl")$, $$,
  $$, $|$, $nonterminal("decl")$, $$,
  // decls
  $nonterminaldef("decls")$, $->$, $terminal("{") nonterminal("decl")_1 terminal(";") dots terminal(";") nonterminal("decl")_n terminal("}")$, $(n >= 0)$,
  // decl
  $nonterminaldef("decl")$, $->$, $nonterminal("gendecl")$, $$,
  $$,$|$, $(nonterminal("funlhs") | nonterminal("pat")) nonterminal("rhs")$,$$,
  // cdecls
  $nonterminaldef("cdecls")$, $->$, $terminal("{") nonterminal("cdecl")_1 terminal(";") dots terminal(";") nonterminal("cdecl")_n terminal("}")$, $(n >= 0)$,
  // cdecl
  $nonterminaldef("cdecl")$, $->$, $nonterminal("gendecl")$, $$,
  $$,$|$, $(nonterminal("funlhs") | nonterminal("var")) nonterminal("rhs")$,$$,
  // idecls
  $nonterminaldef("idecls")$, $->$, $terminal("{") nonterminal("idecl")_1 terminal(";") dots terminal(";") nonterminal("idecl")_n terminal("}")$, $(n >= 0)$,
  // idecl
  $nonterminaldef("idecl")$, $->$, $(nonterminal("funlhs") | nonterminal("var")) nonterminal("rhs")$, $$,
  $$, $|$, $$, [(empty)],
  // gendecl
  $nonterminaldef("gendecl")$, $->$, $nonterminal("vars") terminal("::") [nonterminal("context") terminal("=>")] nonterminal("type")$, [(type signature)],
  $$, $|$, $nonterminal("fixity") [nonterminal("integer")] nonterminal("ops")$, [(fixity declaration)],
  $$, $|$, $$, [(empty declaration)],
  // ops
  $nonterminaldef("ops")$, $->$, $nonterminal("op")_1 terminal(",") dots terminal(",") nonterminal("op")_n$, $(n >= 1)$,
  // vars
  $nonterminaldef("vars")$, $->$, $nonterminal("var")_1 terminal(",") dots terminal(",") nonterminal("var")_n$, $(n >= 1)$,
  // fixity
  $nonterminaldef("fixity")$, $->$, $terminal("infixl") | terminal("infixr") | terminal("infix")$, $$,
  // type
  $nonterminaldef("type")$, $->$, $nonterminal("btype") [terminal("->") nonterminal("type")]$, [(function type)],
  // btype
  $nonterminaldef("btype")$, $->$, $[nonterminal("btype")] nonterminal("atype")$, [(type application)],
  // atype
  $nonterminaldef("atype")$, $->$, $nonterminal("gtycon")$, $$,
  $$,$|$, $nonterminal("tyvar")$, $$,
  $$,$|$, $terminal("(") nonterminal("type")_1 terminal(",") dots terminal(",") nonterminal("type")_k terminal(")")$, [(tuple type, $k >= 2$)],
  $$,$|$, $terminal("[") nonterminal("type") terminal("]")$, [(list type)],
  $$,$|$, $terminal("(") nonterminal("type") terminal(")")$, [(parenthesized constructor)],
  // gtycon
  $nonterminaldef("gtycon")$, $->$, $nonterminal("qtycon")$, $$,
  $$,$|$,$terminal("()")$, [(unit type)],
  $$,$|$,$terminal("[]")$, [(list constructor)],
  $$,$|$,$terminal("(->)")$, [(function constructor)],
  $$,$|$,$terminal("(,") {terminal(",")} terminal(")")$, [(tupling constructors)],
  // context
  $nonterminaldef("context")$, $->$, $nonterminal("class")$, $$,
  $$,$|$,$terminal("(") nonterminal("class")_1 terminal(",") dots terminal(",") nonterminal("class")_n terminal(")")$,$(n >= 0)$,
  // class
  $nonterminaldef("class")$, $->$, $nonterminal("qtycls") nonterminal("tyvar")$, $$,
  $$,$|$,$nonterminal("qtycls") terminal("(") nonterminal("tyvar") nonterminal("atype")_1 dots nonterminal("atype")_n terminal(")")$,$(n >= 1)$,
  // scontext
  $nonterminaldef("scontext")$, $->$, $nonterminal("simpleclass")$, $$,
  $$,$|$,$terminal("(") nonterminal("simpleclass")_1 terminal(",") dots terminal(",") nonterminal("simpleclass")_n terminal(")")$,$(n >= 0)$,
  // simpleclass
  $nonterminaldef("simpleclass")$, $->$, $nonterminal("qtycls") nonterminal("tyvar")$, $$,
  // simpletype
  $nonterminaldef("simpletype")$, $->$, $nonterminal("tycon") nonterminal("tyvar")_1 dots nonterminal("tyvar")_k$, $(k >= 0)$,
  // constrs
  $nonterminaldef("constrs")$, $->$, $nonterminal("constr")_1 terminal("|") dots terminal("|") nonterminal("constr")_n$, $(n >= 1)$,
  // constr
  $nonterminaldef("constr")$, $->$, $nonterminal("con") [terminal("!")] nonterminal("atype")_1 dots [terminal("!")] nonterminal("atype")_k$, [(arity $italic("con") = k$, $k >= 0$)],
  $$,$|$,$(nonterminal("btype") | terminal("!") nonterminal("atype")) nonterminal("conop") (nonterminal("btype") | terminal("!") nonterminal("atype"))$,[(infix $italic("conop")$)],
  $$,$|$,$nonterminal("con") terminal("{") nonterminal("fielddecl")_1 terminal(",") dots terminal(",") nonterminal("fielddecl")_n terminal("}")$,$(n >= 0)$,
  // newconstr
  $nonterminaldef("newconstr")$, $->$, $nonterminal("con") nonterminal("atype")$, $$,
  $$,$|$,$nonterminal("con") terminal("{") nonterminal("var") terminal("::") nonterminal("type") terminal("}")$,$$,
  // fielddecl
  $nonterminaldef("fielddecl")$, $->$, $nonterminal("vars") terminal("::") (nonterminal("type") | terminal("!") nonterminal("atype"))$, $$,
  // deriving
  $nonterminaldef("deriving")$, $->$, $terminal("deriving") ( nonterminal("dclass") | terminal("(") nonterminal("dclass")_1 terminal(",") dots terminal(",") nonterminal("dclass")_n terminal(")"))$, $(n >= 0)$,
  // dclass
  $nonterminaldef("dclass")$, $->$, $nonterminal("qtycls")$, $$,
  // inst
  $nonterminaldef("inst")$, $->$, $nonterminal("gtycon")$, $$,
  $$,$|$,$terminal("(")nonterminal("gtycon") nonterminal("tyvar")_1 dots nonterminal("tyvar")_k terminal(")")$,[($k >= 0$, $italic("tyvars")$ distinct)],
  $$,$|$,$terminal("(") nonterminal("tyvar")_1 terminal(",") dots terminal(",") nonterminal("tyvar")_k terminal(")")$,[($k >= 2$, $italic("tyvars")$ distinct)],
  $$,$|$,$terminal("[") nonterminal("tyvar") terminal("]")$,$$,
  $$,$|$,$terminal("(") nonterminal("tyvar")_1 terminal("->") nonterminal("tyvar")_2 terminal(")")$,[($italic("tyvar")_1$ and $italic("tyvar")_2$ distinct)],
  // fdecl
  $nonterminaldef("fdecl")$, $->$, $terminal("import") nonterminal("callconv") [nonterminal("safety")] nonterminal("impent") nonterminal("var") terminal("::") nonterminal("ftype")$, [(define variable)],
  $$,$|$,$terminal("export") nonterminal("callconv") nonterminal("expent") nonterminal("var") terminal("::") nonterminal("ftype")$,[(expose variable)],
  // callconv
  $nonterminaldef("callconv")$, $->$, $terminal("ccall") | terminal("stdcall") | terminal("cplusplus")$, [(calling convention)],
  $$,$|$,$terminal("jvm") | terminal("dotnet")$,$$,
  $$,$|$,[*system-specific calling conventions*],[],
  // impent
  $nonterminaldef("impent")$, $->$, $[nonterminal("string")]$, [See Section X],
  // expent
  $nonterminaldef("expent")$, $->$, $[nonterminal("string")]$, [See Section X],
  // safety
  $nonterminaldef("safety")$, $->$, $terminal("unsafe") | terminal("safe")$, $$,
  // ftype
  $nonterminaldef("ftype")$, $->$, $nonterminal("frtype")$, $$,
  $$,$|$,$nonterminal("fatype") terminal("->") nonterminal("ftype")$,$$,
  // frtype
  $nonterminaldef("frtype")$, $->$, $nonterminal("fatype")$, $$,
  $$,$|$,$terminal("()")$,$$,
  // fatype
  $nonterminaldef("fatype")$, $->$, $nonterminal("qtycon") nonterminal("atype")_1 dots nonterminal("atype")_k$, $(k >= 0)$,
  // funlhs
  $nonterminaldef("funlhs")$, $->$, $nonterminal("var") nonterminal("apat") { nonterminal("apat") }$, $$,
  $$,$|$,$nonterminal("pat") nonterminal("varop") nonterminal("pat")$,$$,
  $$,$|$,$terminal("(") nonterminal("funlhs") terminal(")") nonterminal("apat") { nonterminal("apat")}$,$$,
  // rhs
  $nonterminaldef("rhs")$, $->$, $terminal("=") nonterminal("exp") [terminal("where") nonterminal("decls")]$, $$,
  $$,$|$,$nonterminal("gdrhs") [terminal("where") nonterminal("decls")]$,$$,
  // gdrhs
  $nonterminaldef("gdrhs")$, $->$, $nonterminal("guards") terminal("=") nonterminal("exp") [nonterminal("gdrhs")]$, $$,
  // guards
  $nonterminaldef("guards")$, $->$, $terminal("|") nonterminal("guard")_1 terminal(",") dots terminal(",") nonterminal("guard")_n$, $(n >= 1)$,
  // guard
  $nonterminaldef("guard")$, $->$, $nonterminal("pat") terminal("<-") nonterminal("infixexp")$, [(pattern guard)],
  $$,$|$,$terminal("let") nonterminal("decls")$,[(local declaration)],
  $$,$|$,$nonterminal("infixexp")$,$$,
  // exp
  $nonterminaldef("exp")$, $->$, $nonterminal("infixexp") terminal("::") [nonterminal("context") terminal("=>")] nonterminal("type")$, [(expression type signature)],
  [],$|$, $nonterminal("infixexp")$,[],
  // infixexp
  $nonterminaldef("infixexp")$, $->$, $nonterminal("lexp") nonterminal("qop") nonterminal("infixexp")$, [],
  [], $|$, $terminal("-") nonterminal("infixexp")$, [(prefix negation)],
  [], $|$, $nonterminal("lexp")$, [],
  // lexp
  $nonterminaldef("lexp")$, $->$, $terminal("\\") nonterminal("apat")_1 dots nonterminal("apat")_n terminal("->") nonterminal("exp")$, [(lambda abstraction, $n >= 1$)],
  [], $|$, $terminal("let") nonterminal("decls") terminal("in") nonterminal("exp")$, [(let expression)],
  [], $|$, $terminal("if") nonterminal("exp") [terminal(";")] terminal("then") nonterminal("exp") [terminal(";")] terminal("else") nonterminal("exp")$, [(conditional)],
  [], $|$, $terminal("case") nonterminal("exp") terminal("of") terminal("{") nonterminal("alts") terminal("}")$, [(case expression)],
  [], $|$, $terminal("do") terminal("{") nonterminal("stmts") terminal("}")$, [(do expression)],
  [], $|$, $nonterminal("fexp")$, [],
  // fexp
  $nonterminaldef("fexp")$, $->$, $[nonterminal("fexp")] nonterminal("aexp")$, [(function application)],
  // aexp
  $nonterminaldef("aexp")$, $->$, $nonterminal("qvar")$, [(variable)],
  [], $|$, $nonterminal("gcon")$, [(general constructor)],
  [], $|$, $nonterminal("literal")$, [],
  [], $|$, $terminal("(") nonterminal("exp") terminal(")")$, [(parenthesized expression)],
  [], $|$, $terminal("(") nonterminal("exp")_1 terminal(",") dots terminal(",") nonterminal("exp")_k terminal(")")$, [(tuple, $k>=2$)],
  [], $|$, $terminal("[") nonterminal("exp")_1 terminal(",") dots terminal(",") nonterminal("exp")_k terminal("]")$, [(list, $k>=1$)],
  [], $|$, $terminal("[") nonterminal("exp")_1 [terminal(",") nonterminal("exp")_2] terminal("..") [nonterminal("exp")_3] terminal("]")$, [(arithmetic sequence)],
  [], $|$, $terminal("[") nonterminal("exp") terminal("|") nonterminal("qual")_1 terminal(",") dots terminal(",") nonterminal("qual")_n terminal("]")$, [(list comprehension, $n>=1$)],
  [], $|$, $terminal("(") nonterminal("infixexp") nonterminal("qop") terminal(")")$, [(left section)],
  [], $|$, $terminal("(") nonterminal("qop")_(chevron.l terminal("-") chevron.r) nonterminal("infixexp") terminal(")")$, [(right section)],
  [], $|$, $nonterminal("qcon") terminal("{") nonterminal("fbind")_1 terminal(",") dots terminal(",") nonterminal("fbind")_n terminal("}")$, [(labeled construction, $n>=0$)],
  [], $|$, $nonterminal("aexp")_(chevron.l nonterminal("qcon") chevron.r) terminal("{") nonterminal("fbind")_1 terminal(",") dots terminal(",") nonterminal("fbind")_n terminal("}")$, [(labeled update, $n>=1$)],
  // qual
  $nonterminaldef("qual")$, $->$, $nonterminal("pat") terminal("<-") nonterminal("exp")$, [(generator)],
  $$, $|$, $terminal("let") nonterminal("decls")$, [(local declaration)],
  $$, $|$, $nonterminal("exp")$, [(guard)],
  // alts
  $nonterminaldef("alts")$,$->$,$nonterminal("alt")_1 terminal(";") dots terminal(";") nonterminal("alt")_n$,$(n >= 1)$,
  // alt
  $nonterminaldef("alt")$,$->$,$nonterminal("pat") terminal("->") nonterminal("exp") [terminal("where") nonterminal("decls")]$,$$,
  $$,$|$,$nonterminal("pat") nonterminal("gdpat") [terminal("where") nonterminal("decls")]$,$$,
  $$,$|$,$$,[(empty alternative)],
  // gdpat
  $nonterminaldef("gdpat")$,$->$,$nonterminal("guards") terminal("->") nonterminal("exp") [nonterminal("gdpat")]$,$$,
  // stmts
  $nonterminaldef("stmts")$,$->$,$nonterminal("stmt")_1 dots nonterminal("stmt")_n nonterminal("exp") [terminal(";")]$,$(n >= 0)$,
  // stmt
  $nonterminaldef("stmt")$,$->$,$nonterminal("exp") terminal(";")$,$$,
  $$,$|$,$nonterminal("pat") terminal("<-") nonterminal("exp") terminal(";")$,$$,
  $$,$|$,$terminal("let") nonterminal("decls") terminal(";")$,$$,
  $$,$|$,$terminal(";")$,[(empty statement)],
  // fbind
  $nonterminaldef("fbind")$,$->$,$nonterminal("qvar") terminal("=") nonterminal("exp")$,$$,
  // pat
  $nonterminaldef("pat")$,$->$,$nonterminal("lpat") nonterminal("qconop") nonterminal("pat")$,[(infix constructor)],
  $$,$|$,$nonterminal("lpat")$,$$,
  // lpat
  $nonterminaldef("lpat")$,$->$,$nonterminal("apat")$,$$,
  $$,$|$,$terminal("-") (nonterminal("integer") | nonterminal("float"))$,[(negative literal)],
  $$,$|$,$nonterminal("gcon") nonterminal("apat")_1 dots nonterminal("apat")_k $,[(arity $italic("gcon") = k$, $k >= 1$)],
  // apat
  $nonterminaldef("apat")$,$->$,$nonterminal("var") [terminal("@") nonterminal("apat")]$,[(as pattern)],
  $$,$|$,$nonterminal("gcon")$,[(arity $italic("gcon") = 0$)],
  $$,$|$,$nonterminal("qcon") terminal("{") nonterminal("fpat")_1 terminal(",") dots terminal(",") nonterminal("fpat")_k terminal("}")$,[(labeled pattern, $k >= 0$)],
  $$,$|$,$nonterminal("literal")$,[],
  $$,$|$,$terminal("_")$,[(wildcard)],
  $$,$|$,$terminal("(") nonterminal("pat") terminal(")")$,[(parenthesized pattern)],
  $$,$|$,$terminal("(") nonterminal("pat")_1 terminal(",") dots terminal(",") nonterminal("pat") terminal(")")$, [(tuple pattern, $k >= 2$)],
  $$,$|$,$terminal("[") nonterminal("pat")_1 terminal(",") dots terminal(",") nonterminal("pat") terminal("]")$, [(list pattern, $k >= 1$)],
  $$,$|$,$terminal("~") nonterminal("apat")$,[(irrefutable pattern)],
  // fpat
  $nonterminaldef("fpat")$,$->$,$nonterminal("qvar") terminal("=") nonterminal("pat")$,$$,
  // gcon
  $nonterminaldef("gcon")$,$->$,$terminal("()")$,$$,
  $$,$|$,$terminal("[]")$,$$,
  $$,$|$,$terminal("(,") { terminal(",")}terminal(")")$,$$,
  $$,$|$,$nonterminal("qcon")$,$$,
  // var
  $nonterminaldef("var")$,$->$,$nonterminal("varid") | terminal("(") nonterminal("varsym") terminal(")")$,[(variable)],
  // qvar
  $nonterminaldef("qvar")$,$->$,$nonterminal("qvarid") | terminal("(") nonterminal("qvarsym") terminal(")")$,[(qualified variable)],
  // con
  $nonterminaldef("con")$,$->$,$nonterminal("conid") | terminal("(") nonterminal("consym") terminal(")")$,[(constructor)],
  // qcon
  $nonterminaldef("qcon")$,$->$,$nonterminal("qconid") | terminal("(") nonterminal("qconsym") terminal(")")$,[(qualified constructor)],
  // varop
  $nonterminaldef("varop")$,$->$,$nonterminal("varsym") | terminal("`") nonterminal("varid") terminal("`")$,[(variable operator)],
  // qvarop
  $nonterminaldef("qvarop")$,$->$,$nonterminal("qvarsym") | terminal("`") nonterminal("qvarid") terminal("`")$,[(qualified variable operator)],
  // conop
  $nonterminaldef("conop")$,$->$,$nonterminal("consym") | terminal("`") nonterminal("conid") terminal("`")$,[(constructor operator)],
  // qconop
  $nonterminaldef("qconop")$,$->$,$nonterminal("gconsym") | terminal("`") nonterminal("qconid") terminal("`")$,[(qualified constructor operator)],
  // op
  $nonterminaldef("op")$,$->$,$nonterminal("varop") | nonterminal("conop")$,[(operator)],
  // qop
  $nonterminaldef("qop")$,$->$,$nonterminal("qvarop") | nonterminal("qconop")$,[(qualified operator)],
  // gconsym
  $nonterminaldef("gconsym")$,$->$,$terminal(":") | nonterminal("qconsym")$,$$,
)

== Fixity Resolution <sec:fixity-resolution>

The following is an example implementation of fixity resolution for
Haskell expressions.
Fixity resolution also applies to Haskell
patterns, but patterns are a subset of expressions so in what follows
we consider only expressions for simplicity.

The function `resolve` takes a list in which the elements are
expressions or operators, i.e. an instance of the $italic("infixexp")$ non-terminal in the context-free grammar.  It returns either `Just e`
where `e` is the resolved expression, or `Nothing` if the input does not represent a valid expression.  In a compiler, of course, it would
be better to return more information about the operators involved for
the purposes of producing a useful error message, but the `Maybe` type will suffice to illustrate the algorithm here.

```haskell
import Control.Monad

type Prec   = Int
type Var    = String

data Op = Op String Prec Fixity
  deriving (Eq,Show)

data Fixity = Leftfix | Rightfix | Nonfix
  deriving (Eq,Show)

data Exp = Var Var | OpApp Exp Op Exp | Neg Exp 
  deriving (Eq,Show)

data Tok = TExp Exp | TOp Op | TNeg
  deriving (Eq,Show)
   
resolve :: [Tok] -> Maybe Exp
resolve tokens = fmap fst $ parseNeg (Op "" (-1) Nonfix) tokens
  where
    parseNeg :: Op -> [Tok] -> Maybe (Exp,[Tok])
    parseNeg op1 (TExp e1 : rest)
       = parse op1 e1 rest
    parseNeg op1 (TNeg : rest)
       = do guard (prec1 < 6)
            (r, rest') <- parseNeg (Op "-" 6 Leftfix) rest
            parse op1 (Neg r) rest'
       where
          Op _ prec1 fix1 = op1

    parse :: Op -> Exp -> [Tok] -> Maybe (Exp, [Tok])
    parse _   e1 [] = Just (e1, [])
    parse op1 e1 (TOp op2 : rest) 
       -- case (1): check for illegal expressions
       | prec1 == prec2 && (fix1 /= fix2 || fix1 == Nonfix)
       = Nothing

       -- case (2): op1 and op2 should associate to the left
       | prec1 > prec2 || (prec1 == prec2 && fix1 == Leftfix)
       = Just (e1, TOp op2 : rest)

       -- case (3): op1 and op2 should associate to the right
       | otherwise
       = do (r,rest') <- parseNeg op2 rest
            parse op1 (OpApp e1 op2 r) rest'
       where
         Op _ prec1 fix1 = op1
         Op _ prec2 fix2 = op2
```

The algorithm works as follows.  At each stage we have a call

```haskell
      parse op1 E1 (op2 : tokens)
```

which means that we are looking at an expression like

```haskell
      E0 `op1` E1 `op2` ...     (1)
```

(the caller holds `E0`).
The job of `parse` is to build the expression
to the right of `op1`, returning the expression and any remaining input.

There are three cases to consider:

1. if `op1` and `op2` have the same precedence, but they do not
  have the same associativity, or they are declared to be nonfix, then
  the expression is illegal.

2. If `op1` has a higher precedence than `op2`, or `op1` and `op2` should left-associate, then we know that the expression to the right
  of `op1` is `E1`, so we return this to the caller.

3. Otherwise, we know we want to build an expression of the form
  #raw("E1 `op2` R").
  To find `R`, we call `parseNeg op2 tokens` to compute
  the expression to the right of `op2`, namely `R` (more about
  `parseNeg` below, but essentially if `tokens` is of the form `(E2 : rest)`,
  then this is equivalent to `parse op2 E2 rest`).  Now, we
  have

  #raw("E0 `op1` (E1 `op2` R) `op3` ...")
  
  where `op3` is the next operator in the input.
  This is an instance of (1) above, so to continue we call parse, with the new #raw("E1 == (E1 `op2` R)").

To initialise the algorithm, we set `op1` to be an imaginary operator
with precedence lower than anything else.  Hence `parse` will consume the whole input, and return the resulting expression.

The handling of the prefix negation operator, `-`, complicates matters
only slightly.  Recall that prefix negation has the same fixity as
infix negation: left-associative with precedence 6.  The operator to
the left of `-`, if there is one, must have precedence lower than 6
for the expression to be legal.  The negation operator itself may
left-associate with operators of the same fixity (e.g. `+`).  So for
example `-a + b` is legal and resolves as `(-a) + b`, but `a + -b` is
illegal.

The function `parseNeg` handles prefix negation.  If we encounter a
negation operator, and it is legal in this position (the operator to
the left has precedence lower than 6), then we proceed in a similar
way to case (3) above: compute the argument to `-` by recursively
calling `parseNeg`, and then continue by calling `parse`.

Note that this algorithm is insensitive to the range and resolution of
precedences.  There is no reason in principle that Haskell should be
limited to integral precedences in the range 1 to 10; a larger range,
or fractional values, would present no additional difficulties.