name: Haskell Report CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  statuses: write

jobs:
  build-typst:
    name: Build Typst Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: typst-community/setup-typst@v5
      - run: typst compile haskell-2010-revised.typ haskell-2010-revised.pdf

  build-stdlib:
    name: Build stdlib haddocks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stdlib
    steps:
      - uses: actions/checkout@v6
      - uses: haskell-actions/setup@v2
      - run: cabal haddock
